name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: leonardoce/release-please-action@sign-off-schema
        id: release
        with:
          release-type: go
          token: ${{ secrets.REPO_PAT }}
